import 'package:flutter/material.dart';
import '../core/theme.dart';
import '../models/book.dart';
import '../services/app_state.dart';
import '../widgets/book_card.dart';
import '../widgets/document_skeleton.dart';

class ExploreScreen extends StatefulWidget { const ExploreScreen({super.key,required this.state,required this.onBook,required this.onAssistant}); final AppState state; final ValueChanged<Book> onBook; final VoidCallback onAssistant; @override State<ExploreScreen> createState()=>_ExploreScreenState(); }
class _ExploreScreenState extends State<ExploreScreen>{ String query=''; String category='';
 @override Widget build(BuildContext context){ final categories=widget.state.books.map((b)=>b.category).where((c)=>c.isNotEmpty).toSet().toList()..sort(); final q=query.toLowerCase().trim(); final results=widget.state.books.where((b)=>(category.isEmpty||b.category==category)&&(q.isEmpty||'${b.title} ${b.author} ${b.description}'.toLowerCase().contains(q))).toList();
 return CustomScrollView(slivers:[
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(18,14,18,8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('Explorer',style:AppTypography.display(size:23,weight:FontWeight.w900))),Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:6),decoration:BoxDecoration(color:AppColors.sky,borderRadius:BorderRadius.circular(12)),child:Text('${results.length} résultats',style:const TextStyle(fontSize:12,fontWeight:FontWeight.w900,color:AppColors.blue)))]),const SizedBox(height:5),const Text('Trouvez un titre, un auteur, une matière ou parcourez les rayons.',style:TextStyle(fontSize:12,color:AppColors.muted)),const SizedBox(height:14),TextField(onChanged:(v)=>setState(()=>query=v),style:const TextStyle(fontSize:13),decoration:InputDecoration(hintText:'Titre, auteur, matière…',hintStyle:const TextStyle(fontSize:12,color:AppColors.muted),prefixIcon:const Icon(AppIcons.search,color:AppColors.blue),fillColor:Theme.of(context).colorScheme.surface,enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide(color:AppColors.blue.withValues(alpha:.14))),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:const BorderSide(color:AppColors.blue,width:1.2)))),const SizedBox(height:10),Material(color:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(15),child:InkWell(onTap:widget.onAssistant,borderRadius:BorderRadius.circular(15),child:Container(padding:const EdgeInsets.all(11),decoration:BoxDecoration(border:Border.all(color:AppColors.blue.withValues(alpha:.12)),borderRadius:BorderRadius.circular(15)),child:const Row(children:[CircleAvatar(radius:17,backgroundColor:AppColors.sky,child:Icon(AppIcons.sparkles,size:17,color:AppColors.blue)),SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Assistant de recherche',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900)),Text('Décrivez votre besoin, l’IA vous oriente.',style:TextStyle(fontSize:12,color:AppColors.muted))])),Icon(AppIcons.chevronRight,size:17,color:AppColors.muted)]))))]))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(18,15,18,8),child:Text('Parcourir les rayons',style:AppTypography.display(size:16,weight:FontWeight.w900)))),
  SliverToBoxAdapter(child:SizedBox(height:45,child:ListView(padding:const EdgeInsets.symmetric(horizontal:16),scrollDirection:Axis.horizontal,children:[_Pill(label:'Tous',selected:category.isEmpty,onTap:()=>setState(()=>category='')),const SizedBox(width:7),...categories.map((c)=>Padding(padding:const EdgeInsets.only(right:7),child:_Pill(label:categoryLabel(c),selected:category==c,onTap:()=>setState(()=>category=c))))]))),
  const SliverToBoxAdapter(child:SizedBox(height:10)),
  SliverToBoxAdapter(child:widget.state.catalogPending?DocumentSkeleton(state:widget.state):results.isEmpty?const _Empty():BookGrid(books:results,favorites:widget.state.favorites,onBook:widget.onBook,onFavorite:(b)=>widget.state.toggleFavorite(b.id))),const SliverToBoxAdapter(child:SizedBox(height:32))]); }
}
class _Pill extends StatelessWidget{const _Pill({required this.label,required this.selected,required this.onTap});final String label;final bool selected;final VoidCallback onTap;@override Widget build(BuildContext context)=>Material(color:selected?AppColors.blue:Theme.of(context).colorScheme.surface,borderRadius:BorderRadius.circular(13),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(13),child:Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:9),decoration:BoxDecoration(borderRadius:BorderRadius.circular(13),border:Border.all(color:selected?AppColors.blue:Theme.of(context).dividerColor.withValues(alpha:.65))),child:Text(label,style:TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:selected?Colors.white:AppColors.muted)))));}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.all(30),child:Column(children:[const Icon(AppIcons.search,size:32,color:AppColors.blue),const SizedBox(height:10),Text('Aucun document trouvé',style:AppTypography.display(size:15,weight:FontWeight.w900)),const SizedBox(height:5),const Text('Essayez un autre mot-clé ou une autre catégorie.',textAlign:TextAlign.center,style:TextStyle(fontSize:12,color:AppColors.muted))]));}
